// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamLeManh_2310900063.Data;

#nullable disable

namespace PhamLeManh_2310900063.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702030546_AddPlmEmployeeTableFix")]
    partial class AddPlmEmployeeTableFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhamLeManh_2310900063.Models.PlmEmployee", b =>
                {
                    b.Property<int>("PlmEmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlmEmpId"));

                    b.Property<string>("PlmEmpLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlmEmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlmEmpStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PlmEmpStatus")
                        .HasColumnType("bit");

                    b.HasKey("PlmEmpId");

                    b.ToTable("PlmEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
